[global]
lang = ["python"]
time = 1

[11948]
lang = ["python"]
time = 2

[14264]
lang = ["python"]
time = 2

[14623]
lang = ["python"]
time = 2

[1003]
lang = ["python"]
time = 0.25

[11257]
lang = ["python"]
time = 2

[14038]
lang = ["python"]
time = 2

[18409]
lang = ["python"]
time = 2

[6764]
lang = ["python"]
time = 2

[13496]
lang = ["python"]
time = 2

[13866]
lang = ["python"]
time = 2

[14173]
lang = ["python"]
time = 2

[15000]
lang = ["python"]
time = 2

[6778]
lang = ["python"]
time = 2


